apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: jobtemplates.tower.ansible.com
spec:
  conversion:
    strategy: None
  group: tower.ansible.com
  names:
    kind: JobTemplate
    listKind: JobTemplateList
    plural: jobtemplates
    singular: jobtemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: JobTemplate is the Schema for the jobtemplates API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              job_template_ask_inventory:
                type: boolean
              job_template_ask_vars:
                type: boolean
              job_template_inventory:
                type: string
              job_template_name:
                type: string
              job_template_playbook:
                type: string
              job_template_project:
                type: string
              tower_auth_secret:
                description: |
                  A k8s secret that contains an access token for AWX. To create an access token see these docs: https://docs.ansible.com/automation-controller/4.1.0/html/userguide/applications_auth.html#add-tokens.
                type: string
            required:
            - tower_auth_secret
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1alpha1
