apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: servicemeshrbacconfigs.rbac.maistra.io
spec:
  conversion:
    strategy: None
  group: rbac.maistra.io
  names:
    categories:
    - istio-io
    - rbac-istio-io
    kind: ServiceMeshRbacConfig
    listKind: ServiceMeshRbacConfigList
    plural: servicemeshrbacconfigs
    singular: servicemeshrbacconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Configuration for Role Based Access Control. See more details
              at: https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1.html'
            properties:
              enforcementMode:
                enum:
                - ENFORCED
                - PERMISSIVE
                type: string
              exclusion:
                description: A list of services or namespaces that should not be enforced
                  by Istio RBAC policies.
                properties:
                  namespaces:
                    description: A list of namespaces.
                    items:
                      format: string
                      type: string
                    type: array
                  services:
                    description: A list of services.
                    items:
                      format: string
                      type: string
                    type: array
                type: object
              inclusion:
                description: A list of services or namespaces that should be enforced
                  by Istio RBAC policies.
                properties:
                  namespaces:
                    description: A list of namespaces.
                    items:
                      format: string
                      type: string
                    type: array
                  services:
                    description: A list of services.
                    items:
                      format: string
                      type: string
                    type: array
                type: object
              mode:
                description: Istio RBAC mode.
                enum:
                - "OFF"
                - "ON"
                - ON_WITH_INCLUSION
                - ON_WITH_EXCLUSION
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
