apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: subjectaccessreviews.authorization.openshift.io
spec:
  conversion:
    strategy: None
  group: authorization.openshift.io
  names:
    kind: SubjectAccessReview
    listKind: SubjectAccessReviewList
    plural: subjectaccessreviews
    singular: subjectaccessreview
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: |-
          SubjectAccessReview is an object for requesting information about whether a user or group can perform an action

          Compatibility level 1: Stable within a major release for a minimum of 12 months or 3 minor releases (whichever is longer).
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          content:
            description: Content is the actual content of the request for create and
              update
            type: object
          groups:
            description: GroupsSlice is optional. Groups is the list of groups to
              which the User belongs.
            items:
              type: string
            type: array
          isNonResourceURL:
            description: IsNonResourceURL is true if this is a request for a non-resource
              URL (outside of the resource hierarchy)
            type: boolean
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          namespace:
            description: Namespace is the namespace of the action being requested.  Currently,
              there is no distinction between no namespace and all namespaces
            type: string
          path:
            description: Path is the path of a non resource URL
            type: string
          resource:
            description: Resource is one of the existing resource types
            type: string
          resourceAPIGroup:
            description: Group is the API group of the resource Serialized as resourceAPIGroup
              to avoid confusion with the 'groups' field when inlined
            type: string
          resourceAPIVersion:
            description: Version is the API version of the resource Serialized as
              resourceAPIVersion to avoid confusion with TypeMeta.apiVersion and ObjectMeta.resourceVersion
              when inlined
            type: string
          resourceName:
            description: ResourceName is the name of the resource being requested
              for a "get" or deleted for a "delete"
            type: string
          scopes:
            description: Scopes to use for the evaluation.  Empty means "use the unscoped
              (full) permissions of the user/groups". Nil for a self-SAR, means "use
              the scopes on this request". Nil for a regular SAR, means the same as
              empty.
            items:
              type: string
            type: array
          user:
            description: User is optional. If both User and Groups are empty, the
              current authenticated user is used.
            type: string
          verb:
            description: 'Verb is one of: get, list, watch, create, update, delete'
            type: string
        required:
        - namespace
        - verb
        - resourceAPIGroup
        - resourceAPIVersion
        - resource
        - resourceName
        - path
        - isNonResourceURL
        - user
        - groups
        - scopes
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
